version: "3.7"
services:
  app:
    build: .
    command: "python3 -m gunicorn -b 0.0.0.0 --workers=2 app"
    volumes:
      - ./:/api
    expose:
      - 8000
    ports:
      - "8000:8000"
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
volumes:
  db_data: