version: "3.7"
services:
  api:
    container_name: api
    build: .
    command: "python3 -m gunicorn -b 0.0.0.0 --workers=2 app"
    volumes:
      - .:/api
    expose:
      - 8000
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
  db:
    container_name: database
    image: mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: altana
      MARIADB_USER: altana
      MARIADB_PASSWORD: password